/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DiscountDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.DiscountModel;

/**
 *
 * @author HUY THUC
 */
public class AddDiscountView extends javax.swing.JFrame {

    /**
     * Creates new form AddDiscountView
     */
    public AddDiscountView() {
        initComponents();
        btnSave.setEnabled(false);
    }
    
    public void validateField()
    {   
        String id = txtID.getText();
        String name = txtName.getText();
        String quantity = txtQuantity.getText();
        String value = txtValue.getText();
        String startday = dateStartDate.getDateFormatString().toString();
        String endday = dateEndDate.getDateFormatString().toString();
        if(!id.equals("") &&!name.equals("") && !quantity.equals("") && !value.equals("")&& !startday.equals("")&& !endday.equals(""))
                btnSave.setEnabled(true);
        else    
              btnSave.setEnabled(false);
        
        
    }

    private void validateFieldValue() {
    String input = txtValue.getText();

    if (!input.isEmpty()) {
        try {
            int value = Integer.parseInt(input);

            if (value < 0 || value > 100) {
                throw new IllegalArgumentException();
            }
        } catch (NumberFormatException e) {
            // Người dùng đã nhập một giá trị không phải số
            JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập các số nguyên từ 0 đến 100.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtValue.setText("");
        } catch (IllegalArgumentException e) {
            // Người dùng đã nhập một số nằm ngoài khoảng từ 0 đến 100
            JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập các số nguyên từ 0 đến 100.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtValue.setText("");
        }
     }
    }
    
    private void validateQuantity() {
    String input = txtQuantity.getText();

    if (!input.isEmpty()) {
        try {
            int quantity = Integer.parseInt(input);

            if (quantity < 0) {
                throw new IllegalArgumentException();
            }
        } catch (NumberFormatException e) {
            // Người dùng đã nhập một giá trị không phải số
            JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập các số nguyên từ 0 đến 100.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtQuantity.setText("");
        } catch (IllegalArgumentException e) {
            // Người dùng đã nhập một số nằm ngoài khoảng từ 0 đến 100
            JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập các số nguyên từ 0 đến 100.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtQuantity.setText("");
        }
    }
}
    private void validateDates() {
    Date startDate = dateStartDate.getDate();
    Date endDate = dateEndDate.getDate();

    if (startDate != null && endDate != null) {
        if (endDate.before(startDate)) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày bắt đầu.", "Lỗi", JOptionPane.ERROR_MESSAGE);
            dateEndDate.setDate(null);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbID = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        lbValue = new javax.swing.JLabel();
        lbStartDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtValue = new javax.swing.JTextField();
        dateStartDate = new com.toedter.calendar.JDateChooser();
        dateEndDate = new com.toedter.calendar.JDateChooser();
        txtID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbID.setText("ID");
        getContentPane().add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 30, 30));

        lbName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbName.setText("Tên mã giảm giá");
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 30));

        lbQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbQuantity.setText("Số lượng");
        getContentPane().add(lbQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 30));

        lbValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbValue.setText("Phần trăm giảm giá");
        getContentPane().add(lbValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, 30));

        lbStartDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbStartDate.setText("Ngày bắt đầu");
        getContentPane().add(lbStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày kết thúc");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, 30));

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 180, 30));

        txtValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValueKeyReleased(evt);
            }
        });
        getContentPane().add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 180, 30));

        dateStartDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateStartDatePropertyChange(evt);
            }
        });
        dateStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateStartDateKeyReleased(evt);
            }
        });
        getContentPane().add(dateStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, 30));

        dateEndDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateEndDatePropertyChange(evt);
            }
        });
        dateEndDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateEndDateKeyReleased(evt);
            }
        });
        getContentPane().add(dateEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 180, 30));

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, 30));

        btnSave.setBackground(new java.awt.Color(255, 255, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 90, 30));

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Cancel");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 90, 30));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(204, 0, 0));
        lbTitle.setText("THÊM MÃ GIẢM GIÁ");
        getContentPane().add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formbg.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
        String input = txtQuantity.getText();
    
    try {
        int quantity = Integer.parseInt(input);
        
        if (quantity >= 0 && quantity <= 100) {
            // Số nằm trong khoảng hợp lệ, thực hiện xử lý tại đây
        } else {
            throw new IllegalArgumentException("Số không nằm trong khoảng từ 0 đến 100.");
        }
    } catch (NumberFormatException e) {
        // Người dùng đã nhập một giá trị không phải số
        JOptionPane.showMessageDialog(this, "Vui lòng nhập vào một số nguyên từ 0 đến 100.", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } catch (IllegalArgumentException e) {
        // Người dùng đã nhập một số nằm ngoài khoảng từ 0 đến 100
        JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        DiscountModel discount = new DiscountModel();
        discount.setDiscountID(txtID.getText());
        discount.setDiscountName(txtName.getText());
        int quantity = Integer.parseInt(txtQuantity.getText());
        discount.setDiscountQuantity(quantity);
        int value = Integer.parseInt(txtValue.getText());
        discount.setDiscountValue(value);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = dateFormat.format(dateStartDate.getDate());
        java.sql.Date sqlDate1 = java.sql.Date.valueOf(dateString);
        discount.setDiscountStart(sqlDate1);
        String dateString1 = dateFormat.format(dateEndDate.getDate());
        java.sql.Date sqlDate2 = java.sql.Date.valueOf(dateString1);
        discount.setDiscountEnd(sqlDate2);
        DiscountDao.save(discount);
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formComponentShown

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtIDKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        validateField();
        validateQuantity();
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtValueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueKeyReleased
        // TODO add your handling code here:
        validateFieldValue();
        validateField();
    }//GEN-LAST:event_txtValueKeyReleased

    private void dateStartDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateStartDateKeyReleased
        // TODO add your handling code here:
        validateField();
       
    }//GEN-LAST:event_dateStartDateKeyReleased

    private void dateEndDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateEndDateKeyReleased
        // TODO add your handling code here:
        validateField();
       
    }//GEN-LAST:event_dateEndDateKeyReleased

    private void txtValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValueActionPerformed

    private void dateStartDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateStartDatePropertyChange
        // TODO add your handling code here:
        validateDates();
    }//GEN-LAST:event_dateStartDatePropertyChange

    private void dateEndDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateEndDatePropertyChange
        // TODO add your handling code here:
        validateDates();
    }//GEN-LAST:event_dateEndDatePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDiscountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDiscountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDiscountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDiscountView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDiscountView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dateEndDate;
    private com.toedter.calendar.JDateChooser dateStartDate;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbValue;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
