/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.GridLayout;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

import com.itextpdf.text.pdf.hyphenation.TernaryTree.Iterator;

import dao.EmployeeDAO;
import model.EmployeeModel;

/**
 *
 * @author MANH THANG
 */
public class EmployeeView extends javax.swing.JFrame {

    private InputForm inputForm;
    private UpdateForm updateForm;
    private boolean ascending = true;
    private HomeView homeView;
    /**
     * Creates new form EmployeeView
     */
    public EmployeeView() {
        initComponents();
    }

    public void setDataEmployeeTable(java.util.Iterator<EmployeeModel> iter) {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        while (iter.hasNext()) {
            EmployeeModel employee = (EmployeeModel) iter.next();
            model.addRow(new Object[] { employee.getId(), employee.getEmployeeName(), employee.getEmployeePhone(),
                    employee.getEmployeeType(), employee.getEmployeeAddress(),
                    employee.getEmployeeHometown(), employee.getEmployeeCID(), employee.getEmployeePosition(),
                    employee.getEmployeeTaxID(), employee.getEmployeeContractID(), employee.getEmployeeEmail(),
                    employee.getEmployeeStatus() });
        }
    }

    public void showEmployeeData() {
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        ArrayList<EmployeeModel> arrayList = EmployeeDAO.getListEmployees();
        setDataEmployeeTable(arrayList.iterator());
    }

    public void showEmployeeDataReverse() {
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        ArrayList<EmployeeModel> arrayList = EmployeeDAO.getListEmployees();
        for (int i = arrayList.size() - 1; i >= 0; i--) {
            EmployeeModel employee = (EmployeeModel) arrayList.get(i);
            model.addRow(new Object[] { employee.getId(), employee.getEmployeeName(), employee.getEmployeePhone(),
                    employee.getEmployeeType(), employee.getEmployeeAddress(),
                    employee.getEmployeeHometown(), employee.getEmployeeCID(), employee.getEmployeePosition(),
                    employee.getEmployeeTaxID(), employee.getEmployeeContractID(), employee.getEmployeeEmail(),
                    employee.getEmployeeStatus() });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        lbIcon = new javax.swing.JLabel();
        lbEmployee = new javax.swing.JLabel();
        lbEmployeeName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lbType = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmployee.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên", "Số điện thoại", "Loại nhân viên", "Địa chỉ", "Quê quán", "Số CCCD", "Vị trí", "Mã số thuế", "Mã hợp đồng", "Email", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.setGridColor(new java.awt.Color(255, 255, 255));
        tblEmployee.setRowHeight(30);
        tblEmployee.setSelectionBackground(new java.awt.Color(255, 255, 204));
        tblEmployee.setSelectionForeground(new java.awt.Color(204, 0, 0));
        tblEmployee.setShowGrid(false);
        tblEmployee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblEmployeeFocusLost(evt);
            }
        });
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 206, 1036, 405));

        lbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pinglogo.png"))); // NOI18N
        jPanel1.add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 133, 82));

        lbEmployee.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        lbEmployee.setForeground(new java.awt.Color(204, 0, 0));
        lbEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmployee.setText("QUẢN LÝ NHÂN VIÊN");
        jPanel1.add(lbEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 41, 476, 53));

        lbEmployeeName.setFont(new java.awt.Font("Open Sans", 0, 15)); // NOI18N
        lbEmployeeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmployeeName.setText("Tên nhân viên");
        jPanel1.add(lbEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 139, 133, 34));

        txtName.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 136, 457, 42));

        btnAdd.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnAdd.setText("Thêm nhân viên");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 136, -1, 43));

        btnUpdate.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(812, 137, 120, 42));

        btnSort.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnSort.setText("Sắp xếp");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });
        jPanel1.add(btnSort, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 137, 110, 42));

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        btnBack.setText("Trở về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 41, 88, 32));

        lbType.setFont(new java.awt.Font("Open Sans", 2, 16)); // NOI18N
        lbType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbType.setText("Admin");
        jPanel1.add(lbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(991, 7, 88, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homebg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
        this.tblEmployee.clearSelection();
        this.btnUpdate.setEnabled(false);
    }//GEN-LAST:event_txtNameMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        homeView = new HomeView();
        homeView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblEmployeeFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_tblEmployeeFocusLost
        // TODO add your handling code here:
        // this.tblEmployee.clearSelection();
        // this.btnUpdate.setEnabled(false);
    }// GEN-LAST:event_tblEmployeeFocusLost

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_txtNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        this.tblEmployee.clearSelection();
        this.btnUpdate.setEnabled(false);
        inputForm = new InputForm(this, true);
        inputForm.setVisible(true);
        showEmployeeDataReverse();
        ascending = false;
    }

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.tblEmployee.clearSelection();
        this.btnUpdate.setEnabled(false);
        if (ascending) {
            showEmployeeDataReverse();
            ascending = false;
        } else {
            showEmployeeData();
            ascending = true;
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateForm = new UpdateForm(this, true);
        int id = Integer.parseInt(tblEmployee.getValueAt(tblEmployee.getSelectedRow(), 0).toString());

        if (id >= 0) {
            updateForm.setEmployee(id);
            updateForm.setVisible(true);
            if (!updateForm.isVisible()) {
                showEmployeeDataReverse();
                this.btnUpdate.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn nhân viên cần sửa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showEmployeeData();
        ascending = true;
        this.btnUpdate.setEnabled(false);
    }// GEN-LAST:event_formComponentShown

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        int index = tblEmployee.getSelectedRow();
        if (index >= 0) {
            this.btnUpdate.setEnabled(true);
        } else {
            this.btnUpdate.setEnabled(false);
        }
    }// GEN-LAST:event_tblEmployeeMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        if (tblEmployee.getSelectedRow() != -1) {
            tblEmployee.clearSelection();
            this.btnUpdate.setEnabled(false);
        }
    }// GEN-LAST:event_jPanel1MouseClicked

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        this.tblEmployee.clearSelection();
        showEmployeeDataByName(txtName.getText());
    }// GEN-LAST:event_txtNameKeyReleased

    private void showEmployeeDataByName(String name) {
        DefaultTableModel model = (DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        ArrayList<EmployeeModel> arrayList = EmployeeDAO.getListEMployeeByName(name);
        setDataEmployeeTable(arrayList.iterator());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeView.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSort;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmployee;
    private javax.swing.JLabel lbEmployeeName;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbType;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
