/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import dao.EmployeeDAO;

/**
 *
 * @author MANH THANG
 */
public class InputForm extends javax.swing.JDialog {

        /**
         * Creates new form InputForm
         */
        public InputForm(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                this.setLocationRelativeTo(null);
        }

        public void showEmployeeType() {
                this.comboBoxType.removeAllItems();
                this.comboBoxType.addItem("Không chọn");
                this.comboBoxType.addItem("parttime");
                this.comboBoxType.addItem("fulltime");
        }

        public void showEmployeePosition() {
                this.comboBoxPosition.removeAllItems();
                try {
                        ArrayList<String> list = EmployeeDAO.getEmployeePosition();
                        this.comboBoxPosition.addItem("Không chọn");
                        for (String string : list) {
                                this.comboBoxPosition.addItem(string);
                                System.out.println(string);
                        }
                } catch (SQLException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                }
        }

        public boolean isValidEmail(String email) {
                String emailRegex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
                return email.matches(emailRegex);
        }
        
        public void setEmployeeID() {
                this.lbEmployeeID.setText(String.valueOf(EmployeeDAO.getMaxID() + 1));
        }

        public void clearInputForm() {
                setEmployeeID();
                this.txtName.setText("");
                this.txtPhone.setText("");
                this.txtCID.setText("");
                this.txtAddress.setText("");
                this.txtHometown.setText("");
                this.txtEmail.setText("");
                this.comboBoxType.setSelectedIndex(0);
                this.comboBoxPosition.setSelectedIndex(0);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbInputEmployee = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtCID = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        lbHometown = new javax.swing.JLabel();
        txtHometown = new javax.swing.JTextField();
        lbCID = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbType = new javax.swing.JLabel();
        comboBoxType = new javax.swing.JComboBox<>();
        lbPosition = new javax.swing.JLabel();
        comboBoxPosition = new javax.swing.JComboBox<>();
        lbTaxID = new javax.swing.JLabel();
        txtTaxID = new javax.swing.JTextField();
        lbContractID = new javax.swing.JLabel();
        txtContractID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        lbID = new javax.swing.JLabel();
        lbEmployeeID = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbInputEmployee.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lbInputEmployee.setForeground(new java.awt.Color(204, 0, 0));
        lbInputEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbInputEmployee.setText("NHẬP THÔNG TIN NHÂN VIÊN");
        lbInputEmployee.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(lbInputEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 721, 39));

        lbName.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbName.setText("Họ và Tên");
        jPanel1.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 65, 73, 35));

        txtName.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 65, 237, 35));

        lbPhone.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbPhone.setText("Số điện thoại");
        jPanel1.add(lbPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 118, 87, 35));

        txtPhone.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 118, 207, 35));

        txtCID.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtCID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCIDFocusLost(evt);
            }
        });
        txtCID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCIDKeyTyped(evt);
            }
        });
        jPanel1.add(txtCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 118, 237, 35));

        txtAddress.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 180, 577, 35));

        lbAddress.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbAddress.setText("Địa chỉ");
        jPanel1.add(lbAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 180, 87, 35));

        lbHometown.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbHometown.setText("Quê quán");
        jPanel1.add(lbHometown, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 242, 87, 35));

        txtHometown.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jPanel1.add(txtHometown, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 242, 207, 35));

        lbCID.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbCID.setText("Số CCCD");
        jPanel1.add(lbCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 126, 73, -1));

        lbEmail.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbEmail.setText("Email");
        jPanel1.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 242, 85, 35));

        txtEmail.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 242, 238, 35));

        lbType.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbType.setText("Loại nhân viên");
        jPanel1.add(lbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 303, -1, 35));

        comboBoxType.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        comboBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTypeActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 303, 207, 35));

        lbPosition.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbPosition.setText("Vị trí");
        jPanel1.add(lbPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 311, 85, -1));

        comboBoxPosition.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jPanel1.add(comboBoxPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 303, 238, 35));

        lbTaxID.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbTaxID.setText("Mã số thuế");
        jPanel1.add(lbTaxID, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 364, 87, 35));

        txtTaxID.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        txtTaxID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(txtTaxID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 364, 207, 35));

        lbContractID.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbContractID.setText("Mã hợp đồng");
        jPanel1.add(lbContractID, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 364, -1, 35));

        txtContractID.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jPanel1.add(txtContractID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 364, 238, 35));

        btnCancel.setBackground(new java.awt.Color(204, 204, 204));
        btnCancel.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnCancel.setText("Huỷ");
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 431, 177, 39));

        lbID.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        lbID.setText("ID Nhân viên");
        jPanel1.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 61, 87, 39));

        lbEmployeeID.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        lbEmployeeID.setForeground(new java.awt.Color(204, 0, 0));
        jPanel1.add(lbEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 61, 243, 39));

        btnAdd.setBackground(new java.awt.Color(255, 255, 204));
        btnAdd.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnAdd.setText("Thêm nhân viên");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 431, 177, 39));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/formbg.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtEmailFocusLost
                // TODO add your handling code here:
                if (!txtEmail.getText().isEmpty()) {
                        if (!isValidEmail(this.txtEmail.getText())) {
                                JOptionPane.showMessageDialog(rootPane, "Sai định dạng email", "Lỗi định dạng",
                                                JOptionPane.ERROR_MESSAGE);
                                this.txtEmail.requestFocus();
                        }
                }
        }// GEN-LAST:event_txtEmailFocusLost

        private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtPhoneFocusLost
                // TODO add your handling code here:
                if (!txtPhone.getText().isEmpty()) {
                        if (this.txtPhone.getText().length() != 10) {
                                JOptionPane.showMessageDialog(rootPane, "Sai định dạng điện thoại", "Lỗi định dạng",
                                                JOptionPane.ERROR_MESSAGE);
                                this.txtPhone.requestFocus();
                        }
                }
        }// GEN-LAST:event_txtPhoneFocusLost

        private void txtCIDFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtCIDFocusLost
                // TODO add your handling code here:
                int length = this.txtCID.getText().length();
                if (!txtCID.getText().isEmpty()) {
                        if (length != 12 && length != 9) {
                                JOptionPane.showMessageDialog(rootPane, "Sai định dạng CCCD", "Lỗi định dạng",
                                                JOptionPane.ERROR_MESSAGE);
                                this.txtCID.requestFocus();
                        }
                }
        }// GEN-LAST:event_txtCIDFocusLost

        

        private void txtCIDKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtCIDKeyTyped
                // TODO add your handling code here:
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) || this.txtCID.getText().length() >= 12) {
                        evt.consume();
                }
        }// GEN-LAST:event_txtCIDKeyTyped

        private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtPhoneKeyTyped
                // TODO add your handling code here:
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) || this.txtPhone.getText().length() >= 10) {
                        evt.consume(); // Không cho phép nhập ký tự và vượt quá độ dài 10
                }
        }// GEN-LAST:event_txtPhoneKeyTyped

        private void comboBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxTypeActionPerformed
                // TODO add your handling code here:
                if (this.comboBoxType.getSelectedItem().toString().equals("fulltime")) {
                        this.txtTaxID.setEnabled(true);
                        this.txtContractID.setEnabled(true);
                } else {
                        this.txtTaxID.setEnabled(false);
                        this.txtContractID.setEnabled(false);
                }
        }// GEN-LAST:event_comboBoxTypeActionPerformed

        private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
                // TODO add your handling code here:
        }// GEN-LAST:event_formWindowClosing

        private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
                // TODO add your handling code here:
                setEmployeeID();
                showEmployeePosition();
                showEmployeeType();
                this.txtTaxID.setEnabled(false);
                this.txtContractID.setEnabled(false);

        }// GEN-LAST:event_formComponentShown

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
                // TODO add your handling code here:
                if (this.txtName.getText().isEmpty() || this.txtPhone.getText().isEmpty()
                                || this.txtCID.getText().isEmpty()
                                || this.txtAddress.getText().isEmpty() || this.txtHometown.getText().isEmpty()
                                || this.txtEmail.getText().isEmpty() || this.comboBoxType.getSelectedIndex() == 0
                                || this.comboBoxPosition.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin", "Lỗi nhập thiếu",
                                        JOptionPane.ERROR_MESSAGE);
                } else {
                        if (this.comboBoxType.getSelectedItem().toString().equals("fulltime")) {
                                if (this.txtTaxID.getText().isEmpty() || this.txtContractID.getText().isEmpty()) {
                                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đầy đủ thông tin",
                                                        "Lỗi nhập thiếu",
                                                        JOptionPane.ERROR_MESSAGE);
                                } else {
                                        if (EmployeeDAO.addEmployee(this.lbEmployeeID.getText(), this.txtName.getText(),
                                                        this.txtPhone.getText(), this.txtCID.getText(),
                                                        this.txtAddress.getText(),
                                                        this.txtHometown.getText(), this.txtEmail.getText(),
                                                        this.comboBoxType.getSelectedItem().toString(),
                                                        this.comboBoxPosition.getSelectedItem().toString(),
                                                        this.txtTaxID.getText(),
                                                        this.txtContractID.getText())) {
                                        } else {
                                                JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thất bại",
                                                                "Thêm thất bại",
                                                                JOptionPane.ERROR_MESSAGE);
                                        }
                                }
                        } else {
                                if (EmployeeDAO.addEmployee(this.lbEmployeeID.getText(), this.txtName.getText(),
                                                this.txtPhone.getText(), this.txtCID.getText(),
                                                this.txtAddress.getText(),
                                                this.txtHometown.getText(), this.txtEmail.getText(),
                                                this.comboBoxType.getSelectedItem().toString(),
                                                this.comboBoxPosition.getSelectedItem().toString(), null, null)) {
                                        JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công",
                                                        "Thêm thành công",
                                                        JOptionPane.INFORMATION_MESSAGE);
                                        this.dispose();
                                } else {
                                        JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thất bại",
                                                        "Thêm thất bại",
                                                        JOptionPane.ERROR_MESSAGE);
                                }
                        }
                }
                // TODO Auto-generated catch block
        }// GEN-LAST:event_btnAddActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(InputForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(InputForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(InputForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(InputForm.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                InputForm dialog = new InputForm(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> comboBoxPosition;
    private javax.swing.JComboBox<String> comboBoxType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbCID;
    private javax.swing.JLabel lbContractID;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmployeeID;
    private javax.swing.JLabel lbHometown;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbInputEmployee;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbPosition;
    private javax.swing.JLabel lbTaxID;
    private javax.swing.JLabel lbType;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtContractID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHometown;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTaxID;
    // End of variables declaration//GEN-END:variables
}
