/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.UserDAO;

/**
 *
 * @author HUY THUC
 */
public class ReportView extends javax.swing.JFrame {
    private HomeView homeView;
    /**
     * Creates new form ReportView
     */
    public ReportView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbYearly = new javax.swing.JLabel();
        lbMonthlyIcon = new javax.swing.JLabel();
        lbDaily = new javax.swing.JLabel();
        lbBestSeller = new javax.swing.JLabel();
        btnYearly = new javax.swing.JButton();
        btnMonthly = new javax.swing.JButton();
        btnBestSeller = new javax.swing.JButton();
        btnDaily = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(204, 0, 0));
        lbTitle.setText("XEM THỐNG KÊ, BÁO CÁO");
        getContentPane().add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 460, -1));

        lbYearly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yearly.png"))); // NOI18N
        getContentPane().add(lbYearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        lbMonthlyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monthly.png"))); // NOI18N
        getContentPane().add(lbMonthlyIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        lbDaily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/daily.png"))); // NOI18N
        getContentPane().add(lbDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        lbBestSeller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bestseller.png"))); // NOI18N
        getContentPane().add(lbBestSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        btnYearly.setBackground(new java.awt.Color(255, 255, 204));
        btnYearly.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        btnYearly.setText("Doanh thu năm");
        btnYearly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearlyActionPerformed(evt);
            }
        });
        getContentPane().add(btnYearly, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 400, 60));

        btnMonthly.setBackground(new java.awt.Color(255, 255, 204));
        btnMonthly.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        btnMonthly.setText("Doanh thu tháng");
        btnMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyActionPerformed(evt);
            }
        });
        getContentPane().add(btnMonthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 400, 60));

        btnBestSeller.setBackground(new java.awt.Color(255, 255, 204));
        btnBestSeller.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        btnBestSeller.setText("Thống kê thức uống bán chạy");
        btnBestSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestSellerActionPerformed(evt);
            }
        });
        getContentPane().add(btnBestSeller, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 400, 60));

        btnDaily.setBackground(new java.awt.Color(255, 255, 204));
        btnDaily.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnDaily.setText("Thống kê chi tiết theo ngày");
        btnDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyActionPerformed(evt);
            }
        });
        getContentPane().add(btnDaily, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 400, 60));

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pinglogo.png"))); // NOI18N
        getContentPane().add(lbIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 80));

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setFont(new java.awt.Font("Open Sans", 1, 15)); // NOI18N
        btnBack.setText("Trở về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 80, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgyellow.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyActionPerformed
       ReportByMonthView dialog = new ReportByMonthView(this, true); // Sử dụng true để đặt dialog form ở chế độ modal
        dialog.setVisible(true);
    }//GEN-LAST:event_btnMonthlyActionPerformed

    private void btnYearlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearlyActionPerformed
        ReportByYearView dialog = new ReportByYearView(this, true); // Sử dụng true để đặt dialog form ở chế độ modal
        dialog.setVisible(true);
    }//GEN-LAST:event_btnYearlyActionPerformed

    private void btnBestSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestSellerActionPerformed
       TKBestSellingView dialog = new TKBestSellingView(this, true); // Sử dụng true để đặt dialog form ở chế độ modal
        dialog.setVisible(true);
    }//GEN-LAST:event_btnBestSellerActionPerformed

    private void btnDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyActionPerformed
        DetailSelling dialog = new DetailSelling(this, true); // Sử dụng true để đặt dialog form ở chế độ modal
        dialog.setVisible(true);
    }//GEN-LAST:event_btnDailyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        homeView = new HomeView();
        if (UserDAO.isEmployee()){
            homeView.EmployeeView();
        } 
        homeView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBestSeller;
    private javax.swing.JButton btnDaily;
    private javax.swing.JButton btnMonthly;
    private javax.swing.JButton btnYearly;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbBestSeller;
    private javax.swing.JLabel lbDaily;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbMonthlyIcon;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbYearly;
    // End of variables declaration//GEN-END:variables
}
