/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.DbOperations;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HUY THUC
 */
public class ReportByYearView extends javax.swing.JDialog {

    /**
     * Creates new form ReportByYearView
     */
    public ReportByYearView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void populateTable() {
    // Thực hiện câu truy vấn để lấy dữ liệu từ cơ sở dữ liệu
    if (txtYear.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập năm cần thống kê");
        return;
    }
    String query = "CALL SP_GetBillPriceByMonth('"+txtYear.getText()+"')";
    System.out.println(query);
    ResultSet resultSet = DbOperations.getData(query);

    try {
        // Lấy DefaultTableModel từ JTable đã tạo sẵn
        DefaultTableModel tableModel = (DefaultTableModel) tblStatisticsYearly.getModel();

        // Xóa các hàng hiện có trong DefaultTableModel
        tableModel.setRowCount(0);

        // Lặp qua các hàng trong ResultSet và thêm vào DefaultTableModel
        while (resultSet.next()) {
            Object[] rowData = {resultSet.getString(1), resultSet.getString(2)};
            tableModel.addRow(rowData);
        }

        // Đóng ResultSet
        resultSet.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatisticsYearly = new javax.swing.JTable();
        btnXem = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        btnExport = new javax.swing.JButton();
        lbYear = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStatisticsYearly.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tháng", "Tổng tiền"
            }
        ));
        tblStatisticsYearly.setRowHeight(30);
        jScrollPane1.setViewportView(tblStatisticsYearly);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 400, 220));

        btnXem.setBackground(new java.awt.Color(255, 255, 204));
        btnXem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXem.setText("Xem");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });
        getContentPane().add(btnXem, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 30));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(204, 0, 0));
        lbTitle.setText("THỐNG KÊ DOANH THU NĂM");
        getContentPane().add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, -1));

        txtYear.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 30));

        btnExport.setBackground(new java.awt.Color(204, 255, 204));
        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setText("Xuất File báo cáo");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        getContentPane().add(btnExport, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 150, 30));

        lbYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbYear.setText("Nhập năm");
        getContentPane().add(lbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgyellow.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnXemActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Thống kê năm "+txtYear.getText()+"");
        MessageFormat footer = new MessageFormat("CoffeeShop");
        try {
            tblStatisticsYearly.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, header);
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportByYearView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportByYearView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportByYearView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportByYearView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReportByYearView dialog = new ReportByYearView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnXem;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbYear;
    private javax.swing.JTable tblStatisticsYearly;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
